### ISSUE TITLE
Config option to disable book at starting

### ISSUE THREAD

**Issue by jawsawn** [ckhgame/VillageBox#13]
I really want to disable that. Please add a config option for it.

**Comment by jawsawn** [comment]
D: noooo don't leave 1.10 completely!!! Please update 1.10.2 . Not many big mods are going to update to 1.11 thus no big modpacks. 

I want to use this in Skyexhange 2.

**Comment by ckhgame** [comment]
Thank you :D
...No worries....1.10.2 will still be the target version... Actually I got some trouble in updating to 1.11, the changes on ItemStack are very annoying.. So it will take longer to update and I think I should stay on 1.10.2 for a while to fix some known bugs. And then directly update to a stable  1.11.2 forge version later.....
