### ISSUE TITLE
[1.10.2-0.6.0] Villagers are not setting home (SMP)

### ISSUE THREAD

**Issue by mr-poyo** [ckhgame/VillageBox#19]
Hello,

Users on my server are saying that they're having issues setting villager homes. When they ask the villager to follow them, the GUI doesn't update as shown in the trailer, but the villager indeed follows. When setting the home in a proper home (7x5x4 box with a solid roof and a door), the chat will say ".. has moved in a new home :D", but in the GUI, the text still says to set home. After this, they cannot progress with the villager. "Follow Me" and "Set Home" are the only options available while the other options are grayed out. Any tips? Thank you!

**Comment by ckhgame** [comment]
Hi clifftrials, 

I'm sorry for the issue, it seems like  a code defect... May I ask you a few questions?
1. are these users using the same minecraft + forge version as the server?
2. can they use the "Set Home" option again to set up a new home?

Thank you 😄

**Comment by mr-poyo** [comment]
Thank you for the response and hard work!

1. Yes, we are using 1.10.2's X.2185 on both the server and client.
2. Same results when selecting "Set Home" again.

-> Works properly in single player
-> We tried a fresh world (SMP) and still had the same issue. 

We'll keep troubleshooting it once we get our base set up. I'll keep you posted if we find anything new.

Please let me know if you need anymore information. Thank you again!

**Comment by ckhgame** [comment]
Thank you for the reply! 

Do you still have the server log of "_We tried a fresh world (SMP) and still had the same issue._"? If possible could you attach it for me?

Thank you again for helping us improve Village Box :D

**Comment by mr-poyo** [comment]
We removed a couple of mods that was giving us a huge issue with block IDs syncing. The two we removed were Not Enough IDs and Conquest Reforged. After starting a new world, without these two mods, the mod appears to be working in SMP (at least the previous mentioned issue is resolved). Not sure if this was the cause, just stating the actions we took. Thanks for helping!
